# Generated by Django 5.0.3 on 2024-03-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_movie_poster_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
